- hosts: web_servers
  become: true
  pre_tasks:
  
    - name: dpkg for Ubuntu
      shell:
        dpkg --configure -a
      when: ansible_distribution == "Ubuntu"

    - name: Install Docker (Ubuntu)
      apt:
        name: docker
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install SDK (Ubuntu)
      shell:
        pip install docker-py

    - name: Adding group to Docker
      shell:
        usermod -aG docker rodriguez

    - name: Enable/Restart Docker (Ubuntu)
      service:
        name: docker
        state: started
        enabled: true

    - name: Creating Directory for Dockerfile
      file:
        path: ./root/demo-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Importing of Dockerfile
      copy:
        src: ./Dockerfile
        dest: ./root/demo-dockerfile/Dockerfile
        owner: root
        group: root
        mode: '0755'
        

